# Generated by Django 5.2.1 on 2025-05-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
    ]
